version: '3'
services:
  mongo:
    image: mongo:4.2.0
    restart: unless-stopped
    container_name: sc-mongo
    ports:
      - 27017:27017
    volumes:
      - /mnt/sda1/mongo:/data/db
  mongo-express:
    image: mongo-express:0.49.0
    container_name: sc-mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
