version: "3"
services:
  redis:
    image: redis:5.0.5
    restart: unless-stopped
    container_name: sc-redis
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/sda1/redis/config:/usr/local/etc/redis
      - /mnt/sda1/redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
