version: '3'
services: 
  graylog:
    image: graylog/graylog:3.1.0
    restart: unless-stopped
    container_name: sc-graylog
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      # - GRAYLOG_HTTP_BIND_ADDRESS=http://192.168.99.108:9000
      - GRAYLOG_HTTP_EXTERNAL_URI=http://192.168.99.108:9000/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://192.168.99.108:9200
      - GRAYLOG_MONGODB_URI=mongodb://192.168.99.108:27017/graylog
      - GRAYLOG_ROOT_TIMEZONE=Asia/Shanghai
    volumes:
      - /mnt/sda1/graylog:/usr/share/graylog/data/journal
