version: '3'
services:
  elasticsearch:
    image: elasticsearch:6.8.2
    restart: unless-stopped
    container_name: sc-elasticsearch
    ports:
      - 9200:9200
    environment:
      - TZ=Asia/Shanghai
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - /mnt/sda1/elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1